FROM debian:jessie

RUN mkdir -p /var/lib/mysql/
RUN mkdir -p /root/composer
RUN mkdir -p /root/.npm
RUN mkdir -p /root/.config/psysh

VOLUME /var/lib/mysql
VOLUME /var/www/html
VOLUME /root/composer
VOLUME /root/.npm
VOLUME /root/.config/psysh
